# Generated by Django 3.0.7 on 2020-06-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
