# Generated by Django 3.0.7 on 2020-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus', '0002_auto_20200609_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceReport',
        ),
    ]
